from aoc import *

#one.main()
#two.main()
#three.main()
#four.main()
#five.main()
#six.main()
#seven.main()
#eight.main()
#nine.main()
#ten.main()
#eleven.main()
#twelve.main()
#thirteen.main()
#fourteen.main()
##fifteen.main()
#sixteen.main()
##seventeen.main()
#eighteen.main()
nineteen.main()